-- Clear bad cache data (only 1000 obscure POIs with IDs under 100000)
DELETE FROM public.tripjack_cities WHERE id < 100000;

-- Seed major Indian and international cities with known Tripjack IDs
INSERT INTO public.tripjack_cities (id, city_name, country_name, type, full_region_name) VALUES
(110203, 'Kolkata', 'India', 'CITY', 'Kolkata, West Bengal, India'),
(130443, 'New Delhi', 'India', 'CITY', 'New Delhi, Delhi, India'),
(131077, 'Mumbai', 'India', 'CITY', 'Mumbai, Maharashtra, India'),
(109519, 'Bangalore', 'India', 'CITY', 'Bangalore, Karnataka, India'),
(127343, 'Chennai', 'India', 'CITY', 'Chennai, Tamil Nadu, India'),
(115936, 'Hyderabad', 'India', 'CITY', 'Hyderabad, Telangana, India'),
(108035, 'Ahmedabad', 'India', 'CITY', 'Ahmedabad, Gujarat, India'),
(131614, 'Pune', 'India', 'CITY', 'Pune, Maharashtra, India'),
(109187, 'Jaipur', 'India', 'CITY', 'Jaipur, Rajasthan, India'),
(114882, 'Goa', 'India', 'CITY', 'Goa, India'),
(128497, 'Lucknow', 'India', 'CITY', 'Lucknow, Uttar Pradesh, India'),
(126235, 'Kochi', 'India', 'CITY', 'Kochi, Kerala, India'),
(130957, 'Chandigarh', 'India', 'CITY', 'Chandigarh, India'),
(113207, 'Guwahati', 'India', 'CITY', 'Guwahati, Assam, India'),
(127668, 'Varanasi', 'India', 'CITY', 'Varanasi, Uttar Pradesh, India'),
(130667, 'Agra', 'India', 'CITY', 'Agra, Uttar Pradesh, India'),
(113572, 'Udaipur', 'India', 'CITY', 'Udaipur, Rajasthan, India'),
(128746, 'Shimla', 'India', 'CITY', 'Shimla, Himachal Pradesh, India'),
(128618, 'Manali', 'India', 'CITY', 'Manali, Himachal Pradesh, India'),
(113684, 'Darjeeling', 'India', 'CITY', 'Darjeeling, West Bengal, India'),
(115609, 'Mysore', 'India', 'CITY', 'Mysore, Karnataka, India'),
(127191, 'Amritsar', 'India', 'CITY', 'Amritsar, Punjab, India'),
(130571, 'Rishikesh', 'India', 'CITY', 'Rishikesh, Uttarakhand, India'),
(131759, 'Dehradun', 'India', 'CITY', 'Dehradun, Uttarakhand, India'),
(131263, 'Bhopal', 'India', 'CITY', 'Bhopal, Madhya Pradesh, India'),
(114199, 'Indore', 'India', 'CITY', 'Indore, Madhya Pradesh, India'),
(128380, 'Visakhapatnam', 'India', 'CITY', 'Visakhapatnam, Andhra Pradesh, India'),
(127543, 'Coimbatore', 'India', 'CITY', 'Coimbatore, Tamil Nadu, India'),
(131567, 'Nagpur', 'India', 'CITY', 'Nagpur, Maharashtra, India'),
(131164, 'Surat', 'India', 'CITY', 'Surat, Gujarat, India'),
(128961, 'Patna', 'India', 'CITY', 'Patna, Bihar, India'),
(113398, 'Ranchi', 'India', 'CITY', 'Ranchi, Jharkhand, India'),
(114666, 'Bhubaneswar', 'India', 'CITY', 'Bhubaneswar, Odisha, India'),
(127876, 'Thiruvananthapuram', 'India', 'CITY', 'Thiruvananthapuram, Kerala, India'),
(109653, 'Srinagar', 'India', 'CITY', 'Srinagar, Jammu and Kashmir, India'),
(115200, 'Leh', 'India', 'CITY', 'Leh, Ladakh, India'),
(130283, 'Jodhpur', 'India', 'CITY', 'Jodhpur, Rajasthan, India'),
(131870, 'Madurai', 'India', 'CITY', 'Madurai, Tamil Nadu, India'),
(110469, 'Ooty', 'India', 'CITY', 'Ooty, Tamil Nadu, India'),
(110085, 'Munnar', 'India', 'CITY', 'Munnar, Kerala, India'),
(109020, 'Dhaka', 'Bangladesh', 'CITY', 'Dhaka, Bangladesh'),
(110529, 'Chittagong', 'Bangladesh', 'CITY', 'Chittagong, Bangladesh'),
(114307, 'Sylhet', 'Bangladesh', 'CITY', 'Sylhet, Bangladesh'),
(115803, 'Coxs Bazar', 'Bangladesh', 'CITY', 'Coxs Bazar, Bangladesh'),
(127614, 'Dubai', 'United Arab Emirates', 'CITY', 'Dubai, United Arab Emirates'),
(130163, 'Bangkok', 'Thailand', 'CITY', 'Bangkok, Thailand'),
(129887, 'Singapore', 'Singapore', 'CITY', 'Singapore'),
(127849, 'Kuala Lumpur', 'Malaysia', 'CITY', 'Kuala Lumpur, Malaysia'),
(131303, 'London', 'United Kingdom', 'CITY', 'London, United Kingdom'),
(130703, 'Paris', 'France', 'CITY', 'Paris, France'),
(128194, 'New York', 'United States', 'CITY', 'New York, United States'),
(114978, 'Tokyo', 'Japan', 'CITY', 'Tokyo, Japan'),
(131447, 'Istanbul', 'Turkey', 'CITY', 'Istanbul, Turkey'),
(131029, 'Bali', 'Indonesia', 'CITY', 'Bali, Indonesia'),
(127297, 'Maldives', 'Maldives', 'CITY', 'Maldives'),
(130823, 'Kathmandu', 'Nepal', 'CITY', 'Kathmandu, Nepal'),
(109341, 'Colombo', 'Sri Lanka', 'CITY', 'Colombo, Sri Lanka'),
(131695, 'Rome', 'Italy', 'CITY', 'Rome, Italy'),
(130527, 'Barcelona', 'Spain', 'CITY', 'Barcelona, Spain'),
(129553, 'Amsterdam', 'Netherlands', 'CITY', 'Amsterdam, Netherlands'),
(128847, 'Hong Kong', 'Hong Kong', 'CITY', 'Hong Kong'),
(131951, 'Sydney', 'Australia', 'CITY', 'Sydney, Australia'),
(114536, 'Phuket', 'Thailand', 'CITY', 'Phuket, Thailand'),
(129207, 'Pattaya', 'Thailand', 'CITY', 'Pattaya, Thailand')
ON CONFLICT (id) DO UPDATE SET
  city_name = EXCLUDED.city_name,
  country_name = EXCLUDED.country_name,
  type = EXCLUDED.type,
  full_region_name = EXCLUDED.full_region_name;